name: Build
on: [push]
jobs:
  packsquash:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          zip_spec_conformance_level: disregard
          size_increasing_zip_obfuscation: true
          percentage_of_zip_structures_tuned_for_obfuscation_discretion: 100
      - name: Download optimized pack
        uses: actions/download-artifact@v3
        with:
          name: Optimized pack
      - name: Tag and create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: action-v${{ github.run_number }}
          files: pack.zip